#!/bin/bash
#
#

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

#export PS1="\n\[$(tput bold)\]\[$(tput setaf 5)\]➜ \[$(tput setaf 6)\]\w\[$(tput setaf 3)\]\$(parse_git_branch) \[$(tput sgr0)\]"
export PS1='\[\e[0;94m\]\u:\w\[\e[0m\] $(parse_git_branch " (%s)")\n⇒ '

if [ $(which fortune) ]; then
  echo ""
  fortune
  echo ""
fi

